#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pipreqs
Version  : 0.4.9
Release  : 1
URL      : https://files.pythonhosted.org/packages/67/63/84409df1acd879d239e53599de2b3df45013e6cf46406fd94e86822635f3/pipreqs-0.4.9.tar.gz
Source0  : https://files.pythonhosted.org/packages/67/63/84409df1acd879d239e53599de2b3df45013e6cf46406fd94e86822635f3/pipreqs-0.4.9.tar.gz
Summary  : Pip requirements.txt generator based on imports in project
Group    : Development/Tools
License  : Apache-2.0
Requires: pipreqs-bin = %{version}-%{release}
Requires: pipreqs-license = %{version}-%{release}
Requires: pipreqs-python = %{version}-%{release}
Requires: pipreqs-python3 = %{version}-%{release}
Requires: docopt
BuildRequires : buildreq-distutils3
BuildRequires : docopt-python
BuildRequires : yarg
BuildRequires : yarg-python

%description
===============================
``pipreqs`` - Generate requirements.txt file for any project based on imports
===============================

%package bin
Summary: bin components for the pipreqs package.
Group: Binaries
Requires: pipreqs-license = %{version}-%{release}

%description bin
bin components for the pipreqs package.


%package license
Summary: license components for the pipreqs package.
Group: Default

%description license
license components for the pipreqs package.


%package python
Summary: python components for the pipreqs package.
Group: Default
Requires: pipreqs-python3 = %{version}-%{release}

%description python
python components for the pipreqs package.


%package python3
Summary: python3 components for the pipreqs package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pipreqs package.


%prep
%setup -q -n pipreqs-0.4.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551109502
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test || :
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pipreqs
cp LICENSE %{buildroot}/usr/share/package-licenses/pipreqs/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pipreqs

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pipreqs/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
