#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pipreqs
Version  : 0.4.10
Release  : 5
URL      : https://files.pythonhosted.org/packages/d1/a0/1e49ca8e560454baaa8e084f6fb76c50afd8e31195d36e5106860820a336/pipreqs-0.4.10.tar.gz
Source0  : https://files.pythonhosted.org/packages/d1/a0/1e49ca8e560454baaa8e084f6fb76c50afd8e31195d36e5106860820a336/pipreqs-0.4.10.tar.gz
Summary  : Pip requirements.txt generator based on imports in project
Group    : Development/Tools
License  : Apache-2.0
Requires: pipreqs-bin = %{version}-%{release}
Requires: pipreqs-license = %{version}-%{release}
Requires: pipreqs-python = %{version}-%{release}
Requires: pipreqs-python3 = %{version}-%{release}
Requires: docopt
Requires: yarg
BuildRequires : buildreq-distutils3
BuildRequires : docopt
BuildRequires : yarg

%description
=============================================================================
``pipreqs`` - Generate requirements.txt file for any project based on imports
=============================================================================

%package bin
Summary: bin components for the pipreqs package.
Group: Binaries
Requires: pipreqs-license = %{version}-%{release}

%description bin
bin components for the pipreqs package.


%package license
Summary: license components for the pipreqs package.
Group: Default

%description license
license components for the pipreqs package.


%package python
Summary: python components for the pipreqs package.
Group: Default
Requires: pipreqs-python3 = %{version}-%{release}

%description python
python components for the pipreqs package.


%package python3
Summary: python3 components for the pipreqs package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pipreqs package.


%prep
%setup -q -n pipreqs-0.4.10
cd %{_builddir}/pipreqs-0.4.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1574345510
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pipreqs
cp %{_builddir}/pipreqs-0.4.10/LICENSE %{buildroot}/usr/share/package-licenses/pipreqs/669a1e53b9dd9df3474300d3d959bb85bad75945
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pipreqs

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pipreqs/669a1e53b9dd9df3474300d3d959bb85bad75945

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
